name: Harbour for Win64 using msvc Curl ssl

#Example of code used to discover where files are stored
#dir C:\vcpkg\*.* /s >output\fulldir\vcpkg.txt

on:
  #We are using 2 triggers, the "push" (meaning when we commit/push to this repo) and "Star" (turning "on" here)
  push:
    branches:
      - main
  #The following run a workflow when someone stars a repository, but later only the repo owner can do the build
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-2019
    
    #The following prevents to execute the action by others and only by maintainers for example.
    if: github.actor == github.event.repository.owner.login

    steps:
      - uses: actions/checkout@v2
    
      - name: Checkout harbour/core repo
        uses: actions/checkout@v2
        with:
          repository: harbour/core
          path: harbour
  
      - name: Installing dependencies
        shell: cmd 
        run: |
          vcpkg.exe install curl:x64-windows
          vcpkg.exe install openssl:x64-windows
          vcpkg integrate install
          
      - name: Fixing Harbour hbssl.hbp
        run: |
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'libeay32','libcrypto-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbp) -replace 'ssleay32','libssl-1_1-x64' | Set-Content -path harbour\contrib\hbssl\hbssl.hbp
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'libeay32','libcrypto' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
          (Get-Content -path harbour\contrib\hbssl\hbssl.hbc) -replace 'ssleay32','libssl' | Set-Content -path harbour\contrib\hbssl\hbssl.hbc
         
      - name: Compile Harbour
        shell: cmd
        run: |
          cd harbour
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          set HB_BUILD_MODE=c
          set HB_USER_PRGFLAGS=-l-
          set HB_BUILD_CONTRIBS=
          set HB_WITH_OPENSSL=c:\vcpkg\packages\openssl-windows_x64-windows\include\
          set HB_WITH_CURL=c:\vcpkg\packages\curl_x64-windows\include
          set HB_OPENSSL_STATIC=yes      
          set HB_STATIC_OPENSSL=yes  
          set HB_STATIC_CURL=yes
          set HB_BUILD_DYN=
          set HB_BUILD_CONTRIB_DYN=
          set HB_COMPILER=msvc64
          win-make.exe          
          
      - name: Create output folders
        shell: cmd
        run: |
          pwd
          mkdir output
          mkdir output\bin
          mkdir output\lib
          mkdir output\include
          mkdir output\envinfo
          mkdir output\vcpkg
          copy D:\a\Harbour_Builds\Harbour_Builds\harbour\bin\win\msvc64\*.exe output\bin
          copy D:\a\Harbour_Builds\Harbour_Builds\harbour\lib\win\msvc64\*.* output\lib
          copy D:\a\Harbour_Builds\Harbour_Builds\harbour\include\*.* output\include
          set >output\envinfo\EnvironmentVariables.txt
          xcopy ${VCPKG_ROOT}\*.* output\vcpkg\ /s
        
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY_MM_DD
 
      - name: Upload Harbour to artifact
        env:
           TIME: "${{ steps.current-time.outputs.formattedTime }}"
        uses: actions/upload-artifact@v2
        with:
          name: harbour_win64_msvc_${{env.TIME}}_${{github.run_number}}
          path: output
          
# originally from https://raw.githubusercontent.com/FiveTechSoft/Harbour_builder/master/.github/workflows/harbour_win64_ADS_msvc.yml